# Generated by Django 2.1.5 on 2019-01-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_img',
            field=models.FileField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
