# Generated by Django 2.1.5 on 2019-03-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, null=True, verbose_name='手机')),
                ('code', models.CharField(max_length=4, null=True, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'zhouju_code',
            },
        ),
    ]
