# Generated by Django 2.1.5 on 2019-01-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_auto_20190123_1448'),
        ('school', '0001_initial'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模拟题附件名')),
                ('filename', models.CharField(max_length=255, verbose_name='存储地址')),
                ('leval', models.CharField(choices=[('gqz', '高起专'), ('gqb', '高起本'), ('zsb', '专升本')], default='gqb', max_length=1, verbose_name='所属层次')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
                ('major_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='major.MajorCates', verbose_name='所属专业')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Schools', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '模拟题',
                'verbose_name_plural': '模拟题',
                'db_table': 'zhouju_aquestions',
            },
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名')),
                ('addtime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('filename', models.CharField(max_length=255, verbose_name='存储地址')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '附件表',
                'verbose_name_plural': '附件表',
                'db_table': 'zhouju_attachments',
            },
        ),
    ]
