# Generated by Django 2.1.5 on 2019-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_aquestions_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquestions',
            name='filename',
            field=models.FileField(upload_to='file', verbose_name='存储地址'),
        ),
        migrations.AlterField(
            model_name='attachments',
            name='filename',
            field=models.FileField(upload_to='enclosure', verbose_name='存储地址'),
        ),
    ]
