# Generated by Django 2.1.5 on 2019-02-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20190129_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquestions',
            name='major_cate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='major.Majors', verbose_name='所属专业'),
        ),
    ]
