# Generated by Django 2.1.5 on 2019-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20190222_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquestions',
            name='leval',
            field=models.IntegerField(choices=[(0, '高起专'), (1, '高起本'), (2, '专升本')], default=0, verbose_name='所属层次'),
        ),
    ]
