# Generated by Django 2.1.5 on 2019-02-25 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('user', '0003_emailverifyrecord'),
        ('server', '0007_auto_20190222_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='provinces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provinces', to='user.Provinces', verbose_name='学习中心所在省份'),
        ),
        migrations.AddField(
            model_name='centers',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='school', to='school.Schools', verbose_name='学习中心所属院校'),
        ),
    ]
