# Generated by Django 2.1.5 on 2019-02-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20190225_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='centers',
            name='postcode',
            field=models.CharField(max_length=255, null=True, verbose_name='邮编'),
        ),
    ]
