# Generated by Django 2.1.5 on 2019-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
    ]
