# Generated by Django 2.1.5 on 2019-01-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20190118_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='admin_img',
            field=models.FileField(default='', upload_to='media'),
            preserve_default=False,
        ),
    ]
