# Generated by Django 2.1.5 on 2019-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='count',
            field=models.BigIntegerField(null=True, verbose_name='报读人数'),
        ),
        migrations.AlterField(
            model_name='majors',
            name='detail',
            field=models.TextField(null=True, verbose_name='专业介绍'),
        ),
        migrations.AlterField(
            model_name='majors',
            name='times',
            field=models.FloatField(null=True, verbose_name='学制'),
        ),
    ]
