# Generated by Django 2.1.5 on 2019-02-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0002_auto_20190123_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majors',
            options={'ordering': ['-major_name'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
    ]
