# Generated by Django 2.1.5 on 2019-02-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0003_auto_20190211_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorcates',
            options={'ordering': ['-catename'], 'verbose_name': '专业分类', 'verbose_name_plural': '专业分类'},
        ),
    ]
