# Generated by Django 2.1.5 on 2019-02-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0004_auto_20190211_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majors',
            options={'ordering': ['id'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
    ]
