# Generated by Django 2.1.5 on 2019-02-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0005_auto_20190212_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majors',
            options={'ordering': ['major_name'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
    ]
