# Generated by Django 2.1.5 on 2019-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0006_auto_20190212_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='level',
            field=models.IntegerField(choices=[('0', '高起专'), ('1', '高起本'), ('2', '专升本')], default=0, verbose_name='层次'),
        ),
    ]
