# Generated by Django 2.1.5 on 2019-02-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0008_auto_20190214_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='majors',
            name='major_image',
            field=models.FileField(null=True, upload_to='media', verbose_name='专业封面图'),
        ),
    ]
