# Generated by Django 2.1.5 on 2019-02-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0009_majors_major_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='majors',
            name='is_net',
            field=models.BooleanField(default=False, verbose_name='是否网络专业'),
        ),
    ]
