# Generated by Django 2.1.5 on 2019-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('major', '0011_auto_20190304_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majors',
            name='major_image',
            field=models.FileField(null=True, upload_to='media', verbose_name='专业封面图'),
        ),
    ]
