# Generated by Django 2.1.5 on 2019-01-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_emailverifyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='院校特征名称')),
                ('notes', models.TextField(null=True, verbose_name='院校特征说明')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '院校特征表',
                'verbose_name_plural': '院校特征',
                'db_table': 'zhouju_school_features',
            },
        ),
        migrations.CreateModel(
            name='SchoolIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesezhuanye', models.TextField(verbose_name='特色专业')),
                ('yuanxiaojieshao', models.TextField(verbose_name='院校介绍')),
                ('zhaoshengduixiang', models.TextField(verbose_name='招生对象')),
                ('zhaoshengzhuanye', models.TextField(verbose_name='招生专业')),
                ('baomingbanfa', models.TextField(verbose_name='报名办法')),
                ('ruxuefangshi', models.TextField(verbose_name='入学方式')),
                ('ruxueceshi', models.TextField(verbose_name='入学测试')),
                ('ruxuezigeshencha', models.TextField(verbose_name='入学资格审查')),
                ('luqujiaofei', models.TextField(verbose_name='录取缴费')),
                ('jiaoxuejixuexi', models.TextField(verbose_name='教学及学习')),
                ('zhongdianzhuanyekechengshezhi', models.TextField(verbose_name='重点专业课程设置')),
                ('tongkao', models.TextField(verbose_name='统考')),
                ('biyezhengshu', models.TextField(verbose_name='毕业证书学位证书')),
                ('biyeimage', models.FileField(upload_to='media', verbose_name='毕业证图片地址')),
                ('xueweiimage', models.FileField(upload_to='media', verbose_name='学位证图片地址')),
            ],
            options={
                'verbose_name': '院校招生简章',
                'verbose_name_plural': '院校招生简章',
                'db_table': 'zhouju_school_intro',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='院校名称')),
                ('banner', models.FileField(null=True, upload_to='media', verbose_name='院校banner图')),
                ('description', models.TextField(verbose_name='院校描述')),
                ('motto', models.TextField(null=True, verbose_name='校训')),
                ('emblem', models.FileField(null=True, upload_to='media', verbose_name='校徽')),
                ('enrol_notes', models.TextField(null=True, verbose_name='报名须知')),
                ('diploma_images', models.FileField(null=True, upload_to='media', verbose_name='毕业证图片地址')),
                ('degree_images', models.FileField(null=True, upload_to='media', verbose_name='学位证图片地址')),
                ('is_985', models.BooleanField(default=False, verbose_name='是否是985')),
                ('is_211', models.BooleanField(default=False, verbose_name='是否是211')),
                ('is_double', models.BooleanField(default=False, verbose_name='是否是双一流')),
                ('brief', models.TextField(null=True, verbose_name='招生简章')),
                ('exam', models.TextField(null=True, verbose_name='考试与毕业')),
                ('count', models.BigIntegerField(null=True, verbose_name='累计报读人数')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
                ('sch_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sch_city', to='user.Citys', verbose_name='院校所在城市')),
                ('sch_pro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sch_pro', to='user.Provinces', verbose_name='院校所在省份')),
                ('scholl_feature', models.ManyToManyField(to='school.SchoolFeatures', verbose_name='学校特性')),
            ],
            options={
                'verbose_name': '院校表',
                'verbose_name_plural': '院校列表',
                'db_table': 'zhouju_schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255, verbose_name='类型名称')),
                ('notes', models.TextField(null=True, verbose_name='分类说明')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '院校类型表',
                'verbose_name_plural': '院校类型',
                'db_table': 'zhouju_school_type',
            },
        ),
        migrations.AddField(
            model_name='schools',
            name='school_type',
            field=models.ManyToManyField(to='school.SchoolType', verbose_name='学校类型'),
        ),
        migrations.AddField(
            model_name='schoolintro',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Schools', verbose_name='院校id'),
        ),
    ]
