# Generated by Django 2.1.5 on 2019-01-24 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major', '0002_auto_20190123_1448'),
        ('user', '0003_emailverifyrecord'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=255, verbose_name='真实姓名')),
                ('idcard', models.CharField(max_length=18, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=255, verbose_name='电话')),
                ('status', models.CharField(choices=[('wfk', '未付款'), ('yfk', '已付款'), ('ylq', '已录取'), ('ysx', '已失效')], default='wfk', max_length=1, verbose_name='付款录取状态')),
                ('is_status', models.BooleanField(default=True, verbose_name='状态')),
                ('majar_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='major.Majors', verbose_name='专业id')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Schools', verbose_name='院校id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Users', verbose_name='用户id')),
            ],
        ),
    ]
