# Generated by Django 2.1.5 on 2019-01-24 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '报名订单信息', 'verbose_name_plural': '报名订单信息'},
        ),
        migrations.AlterModelTable(
            name='orders',
            table='zhouju_orders',
        ),
    ]
