# Generated by Django 2.1.5 on 2019-01-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190124_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('wfk', '未付款'), ('yfk', '已付款'), ('ylq', '已录取'), ('ysx', '已失效')], default='wfk', max_length=3, verbose_name='付款录取状态'),
        ),
    ]
