# Generated by Django 2.1.5 on 2019-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190124_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
    ]
